---
name: Tests

on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-22.04"
            setup-python-action: "v2"
          - os: "ubuntu-24.04"
            setup-python-action: "v5"

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@${{ matrix.setup-python-action }}
        with:
          python-version: "3.12"
      - name: Install latest pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Install dependencies
        run: |
          PACKAGES=('mock' 'pytest' 'pytest-django' 'pytest-cov' 'django-environ' 'setuptools_scm' 'pyupgrade' 'psycopg2-binary')
          PACKAGES+=("Django~=5.0");

          PGPASSWORD="postgres" psql -c 'create database django_guardian;' -h localhost -U postgres;
          PGPASSWORD="postgres" psql -c 'create database test_django_guardian;' -h localhost -U postgres;

          python -m pip install --upgrade --upgrade-strategy=only-if-needed ${PACKAGES[*]};
      - name: Ensure no version conflicts exist
        run: pip check
      - name: Lint modern PY3 syntax
        run: find . -name '*.py' | xargs pyupgrade --py3-only

      - name: Code tests (with PostgreSQL)
        run: |
          export DATABASE_URL=postgres://postgres:postgres@localhost/django_guardian
          python ./setup.py --version
          py.test guardian/testapp/tests/test_mixins.py::TestViewMixins::test_list_permission --cov=guardian
          cat database.log
